### ISSUE TITLE
Collector List language (online, offline)

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#14]
Keep language consistent.

We refer to collector status as "Online" or "Offline". The header for Collector List should be consistent with this, and changed from "UP|DOWN" to "Online|Offline"

**Comment by mattttt** [comment]
Fixed in Pull Request mattttt-patch-tinyalpha-1

**Comment by mattttt** [comment]
Pull request not properly submitted for mattttt-patch-tinyalpha, so reopening issue and will submit a new pull request.

**Comment by mattttt** [comment]
Trent updated this in his commit earlier today in Pull Request #36

**Comment by bulletfactory** [comment]
Yep, should have put issue # in my commit message.

**Comment by bulletfactory** [comment]
collectors now all display online/offline consistently in the frontend, however, the status in the database needs to be updated.

The pull-down at the top of the collectors page still shows up/down for status.

**Comment by nopzor1200** [comment]
I'm going to leave this unassigned and unactionable for now; let's let all this language (up vs down, online vs offline, ok vs error, etc) just "sink in" for a while and circle back in a couple of weeks

**Comment by bulletfactory** [comment]
Let's think about collapsing everything into "disable" | "enable", it might be simpler all around
